language: node_js
node_js:
  - "8.1.0"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - ARCH=x86
        - ARCH_NAME=ia32
      compiler: "g++-5 -m32"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - gcc-multilib
            - gcc-5
            - g++-5
            - gcc-5-multilib
            - g++-5-multilib
            - libgtk2.0-0:i386
            - libx11-dev:i386
            - libx11-xcb-dev:i386
            - libxtst6:i386
            - libxkbfile-dev:i386
            - libxss1:i386
            - libgconf-2-4:i386
            - libdbus-1-dev:i386
            - libasound2:i386
            - libcap-dev:i386
            - libcups2:i386
            - libnss3:i386
            - icnsutils
            - graphicsmagick
            - xz-utils
            - tree
    - os: linux
      dist: trusty
      sudo: required
      env:
        - ARCH=x64
        - ARCH_NAME=x64
      compiler: "g++-5 -m64"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - gcc-5
            - g++-5
            - libgtk2.0-0
            - libx11-dev
            - libxkbfile-dev
            - icnsutils
            - graphicsmagick
            - xz-utils
            - tree
    - os: osx
      env:
        - ARCH=x64
        - ARCH_NAME=x64

branches:
  only:
    - devel

install:
  - rvm get stable
  - if [ `uname` = "Darwin" ]; then
      brew install tree;
    fi
  - export APP="GrandView"
  - export TAG="$TRAVIS_TAG"
  - export OS="$TRAVIS_OS_NAME"
  - export VERSION=$(echo $TRAVIS_TAG | cut -d 'v' -f 2)
  - curl https://install.meteor.com/ | /bin/sh
  - npm install

script:
  - ./.scripts/travis_script.sh

cache:
  directories:
  - .cache

notifications:
  email:
    on_success: never
    on_failure: always

after_failure:
  - ./.scripts/travis_print_env.sh

after_success:
  - ./.scripts/travis_print_env.sh
