language: node_js
node_js:
  - "0.10.41"

sudo: required

# multiple oses when nodejs env comes to osx on travis
#os:
#  - linux
#  - osx

env:
  - ARCH=x64 ARCH_NAME=x64
  # - ARCH=x86 ARCH_NAME=ia32

branches:
  only:
    # only tags on the form vx.x.x or vx.x.xxx and so on
    - /v\d+\.\d+\.\d+/

# Install scripts.
install:
  # Install meteor
  - curl https://install.meteor.com/ | /bin/sh
  # Install correct node version
  # - NVER=`node -v`
  # - wget http://nodejs.org/dist/${NVER}/node-${NVER}-${TRAVIS_OS_NAME}-${ARCH}.tar.gz
  # - tar xf node-${NVER}-${TRAVIS_OS_NAME}-${ARCH}.tar.gz
  # - export PATH=$(pwd)/node-${NVER}-${TRAVIS_OS_NAME}-${ARCH}/bin:$PATH
  # - if [[ "${ARCH}" == 'x86' ]]; then sudo apt-get update && sudo apt-get -y install gcc-multilib g++-multilib; fi
  # - if [[ "${ARCH}" == 'x86' ]]; then CC=gcc-4.6 CXX=g++-4.6 npm install --build-from-source; else npm install; fi
  # setup GrandView
  - npm install

script:
  # avoid the scss error
  - node scripts/scss
  # Pack and build
  - npm run build:linux:$ARCH
  # - npm run build:osx
  # - nvm install 0.12.7
  # - nvm use 0.12.7
  # - npm run pack:osx
  # zip it up
  # Linux
  - tar -zcf GrandView-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-${ARCH_NAME}.tar.gz -C dist/linux/${ARCH}/GrandView-${TRAVIS_OS_NAME}-${ARCH_NAME} .
  # Mac
  # - tar -zcf GrandView-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-${ARCH}.tar.gz dist/linux/x64/GrandView.dmg

cache:
  directories:
  - cache

# deploy:
#   provider: releases
#   api-key:
#     secure: "HvFmSEsiOIFXpOTwCAd7bIReM45XjL90pq1WDiFOPtkTPv1CvvZFCbuY9+Hwp5QAiASEbdCZIucq3q3rBNmmGhOB9D+wQ+Rj+AciJDtB0WP72sVrGZLM2nPk1+hbn402SpH6WOLUygw1NxZqO9FfjcOMZwida8KLLDp/SDP3OtBYm5Jk+9Nh1cRht73wXd+LRqhuVdCh7GRCgg182L8cfIMq0NztKE297bXMjhk/teV9984bHf1BKXWgwQ5DhSgEtW7xMat2eWFaIGGCjZ3e5gQkSOk1an7QG1NRq1ehYwWa3uuzTeUKxCYwqI6jnbzCX+FzEUuV7Lgr6xPWyukF4faZqDzhsnkqiExZLaqQ4QYWURf5kgT1L7/kkAJdpX3utXM7ElQnou1AzG/jL70kquqgUCCBpEOJcS//hbMHy/VT6BfaH4HkdUrej0geaIdFjV0y6nTC3VIeRYah2VBH/L11UfLc5kOnPu5I86xHFmxiQ/DSMQmuFYTV5/hEkvSh8JqW8nlwdqFzbmw080ZveUogUIn/3ARJgV3HcgJW2rEeCjqut2uNVEkCC9gO5cAjCfIB+Bkao5A0IsdxjguhqdTGnZlMKYz9i/+Wef0H0nMfoRyZS3D4U/NARuFxZXc35wQx8EDwAlhRewgehZmgKtjqV9tBE26L24l6t4xer/8="
#   file:
#     - "GrandView-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-${ARCH_NAME}.tar.gz"
#   skip_cleanup: true
#   on:
#     tags: true

deploy:
  provider: releases
  api_key:
    secure: vHqlOdMB9CCg9iRfWyFj3l4DoBH5EbXewa050i0BrzESFZOFaLYEmIUd9bo8p+c/xkHdIWL4c3mgK4LsWV23DMB153rPfhP9OmFZ9hXnQmk2zsfQqod07qxY7kdlvINR9Y3+9wjkRBDW8SsRX4vrFAHhYV2NHZW2P1Zz/MJ0sTfL/U3XTUvuXBXi9Qkeiq2lfF7c6xuaIbCGjxmAoWiPZi/cvsT9hbjbiiEgRZv7+HhzcvBf83E7scbuNO2HJ0tePe39ml7++7GZaBRf7x4b/j/CdsPjwO5cxCirKQyDn+3Fz63ss0KoXiW/WkmyAjDMpg6p5I/IER/hWldeXEHKItZcg1N2apM1N4zIaOsBW13ydWY21+O51HDYgNS4JqguAw0OI7fhPgtQjLdEmlKpaqg4envd08n3n7sqLUfThL0Tn0rchF80xyHU9miULqK+xH1FNae+tDRfp76t7GX/ZV3Xpu0LYKAv3sWzo/JF0VQohWd++K9KiauApqGMTd+MLcwFsB0JELz2beyTUKgqrHQzmRJCeCZQqLvDg+YUPzZuMwTKP/n2rK1E4VXt/0q0erZ8K+dSav2/2eqZvoi+byzQuhloQxCk+REeBScAy5MTAqiFuKoA/3FcOcb8T5vX962wBndf+PL7wEbkPnnaX3Rq14dHdtcYrfNWxDcERCA=
  file: GrandView-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-${ARCH_NAME}.tar.gz
  skip_cleanup: true
  on:
    repo: bompi88/grand-view
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always
