language: node_js
node_js:
  - "8.1.0"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - ARCH=x86
        - ARCH_NAME=ia32
      compiler: "g++-5 -m32"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - gcc-multilib
            - gcc-5
            - g++-5
            - gcc-5-multilib
            - g++-5-multilib
            - libgtk2.0-0:i386
            - libx11-dev:i386
            - libx11-xcb-dev:i386
            - libxtst6:i386
            - libxkbfile-dev
            - icnsutils
            - graphicsmagick
            - xz-utils
    - os: linux
      dist: trusty
      sudo: required
      env:
        - ARCH=x64
        - ARCH_NAME=x64
      compiler: "g++-5 -m64"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - gcc-5
            - g++-5
            - libgtk2.0-0
            - libx11-dev
            - libxkbfile-dev
            - icnsutils
            - graphicsmagick
            - xz-utils
    - os: osx
      env:
        - ARCH=x64
        - ARCH_NAME=x64

branches:
  only:
    - /v\d+\.\d+\.\d+(-beta.\d+)?/

install:
  - rvm get stable
  - export APP="GrandView"
  - export TAG="$TRAVIS_TAG"
  - export OS="$TRAVIS_OS_NAME"
  - export VERSION=$(echo $TRAVIS_TAG | cut -d 'v' -f 2)
  - curl https://install.meteor.com/ | /bin/sh
  - npm install
  - printenv

script:
  - printenv
  - ./.scripts/travis_script.sh

cache:
  directories:
  - .cache

before_deploy:
  - printenv
  - ./.scripts/travis_before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure:  RVS2+TbbMDWOjS+wTxcwvtp6/oiz8mgIiarODGrgY/Nf2wxNy04dFIAt+mrj05c8dUopfihVFZZRjRTGzAhzpmkFhUSvhknikdhR9DOQrWmYgUPXbHjbGEluF4BcPhcIrj5J0wXG7RO4GHiT7+RVMhNBcHEzzw1qevWVB9Lnevk+4SKeNHJoNSXRq3nk2eD289zOccLW/pwVW5rPL9AfRtpJq5YnlPHGXxWJ9udcSXYZGpHi/yzsinTE9TuAxNvq75eV0HDQgA6bCe+m0fc3+x/TGWE6E+fulGhyjd42XV0i7abdbINj4yMFaVhS/H6PU7rtp7MXbaJrjks0uBs7wEowgHXHIFqHbFuZeZE3yMJbluWuNWmMjra+NvWezG3kMZycVsNN51AUm8GqP25q8YpoQKiJ0ZfZBtoKfLo4Cj38w7TEptyBFsSxPT2kOYRK8we6t+PbDsgNAo9fQmJc5NU4Y6sRvgPWP5CglBvIKRFNpTv+ISai+bYX2DwE4yD8TFQ9CZ9ykFjEmHFC7+XUCSsjeoVQtCNvN2Jk0oQNX7E+oHO1qvhQ3tgJI4dP94WQfGoG/G+z0VESd6J0iAECoB7d7Lt0K3mBvdl/e7epS7wa2a3eG8GOboxfiqJOzHEV34uPBXIS/EPp4uq3NxnugH9OIa5mHM0Fxw8iWoBbnoA=
  file_glob: true
  file:
    - .releases/*
  skip_cleanup: true
  on:
    repo: bompi88/grand-view
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always

after_failure:
  - uname -a
  - ls .dist
  - ls .releases
  - npm --version
  - meteor --version
  - node --version
  - g++ -v
  - gcc -v
