language: node_js
node_js:
  - "0.10.36"

sudo: required

# multiple oses when nodejs env comes to osx on travis
#os:
#  - linux
#  - osx

branches:
  only:
    # only tags on the form vx.x.x or vx.x.xxx and so on
    - /v\d+\.\d+\.\d+/

before_install:
  - export ARCH=$(uname -m)

# Install scripts.
install:
  # Install meteor
  - curl https://install.meteor.com/ | /bin/sh
  # setup GrandView
  - npm install

script:
  # avoid the scss error
  - node scripts/scss
  # Pack and build
  - npm run build:linux
  # - npm run build:osx
  # - nvm install 0.12.7
  # - nvm use 0.12.7
  # - npm run pack:osx
  # zip it up
  # Linux
  - tar -zcf GrandView-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-${ARCH}.tar.gz -C dist/linux/x64/GrandView-linux-x64 .
  # Mac
  # - tar -zcf GrandView-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-${ARCH}.tar.gz dist/linux/x64/GrandView.dmg

cache:
  directories:
  - cache

deploy:
  provider: releases
  api-key:
    secure: "3a3d2c2f84a3c313443997648f3c3b8172bc5aad"
  file:
    - "GrandView-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-${ARCH}.tar.gz"
    # - "GrandView-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-${ARCH}.tar.gz"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always
