environment:
  nodejs_version: "7.10.0"

branches:
  only:
    - /v\d+\.\d+\.\d+(-beta.\d+)?/

platform:
  - x86
  - x64

install:
  - ps: $env:app_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Install-Product node $env:nodejs_version $env:platform
  # Install modules
  - npm install
  # Install build tools
  - npm install --global --production windows-build-tools
  # Download Meteor
  - ps: Start-FileDownload 'https://s3.amazonaws.com/meteor-windows/InstallMeteor.exe'
  # Install meteor
  - .\installMeteor.exe /passive
  # Restart
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer -Force

build_script:
  - echo %platform%
  - npm run build:win:%platform%

after_build:
  - 7z a GrandView-%APPVEYOR_REPO_TAG_NAME%-win32-%platform%-installer.zip "%APPVEYOR_BUILD_FOLDER%\.dist\GrandView Setup $env:package_version.exe"

deploy:
  provider: GitHub
  auth_token:
    secure: tNMKx8kVItLg0Henj9BJJNB+IUTkaa1ScGiJ7WBq6/TxST6l7MhHGe4k0omB6H5V
  artifact: "GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform),GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)-installer"
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

artifacts:
  - path: dist\windows\x86\GrandView-win32-ia32
    name: GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)

  - path: GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)-installer.zip
    name: GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)-installer
