environment:
  nodejs_version: "0.10.36"

branches:
  only:
    - prod
    - /v\d+\.\d+\.\d+/

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Setup
  - npm install
  # download Meteor
  - ps: Start-FileDownload 'https://s3.amazonaws.com/meteor-windows/InstallMeteor.exe'
  # install meteor
  - .\installMeteor.exe /passive
  # download NSIS
  - ps: choco install -y nsis -pre
  # Restart
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer -Force

build_script:
  - ps: Start-Sleep -s 5
  - set PATH=C:\Program Files (x86)\NSIS;%PATH%
  # For some reason it is necessary to split up the commands
  - node scripts/download --platform=win32 --arch=x86
  - node scripts/prepare --platform=win32 --arch=x86
  - npm run clean:win
  - npm run build:win
  # Update node
  - ps: Update-NodeJsInstallation 0.12.7
  - npm run pack:win

after_build:
  - 7z a GrandView-%APPVEYOR_REPO_TAG_NAME%-win32-ia32-installer.zip "%APPVEYOR_BUILD_FOLDER%\dist\windows\x86\GrandView Setup.exe"

deploy:
  provider: GitHub
  auth_token:
    secure: tNMKx8kVItLg0Henj9BJJNB+IUTkaa1ScGiJ7WBq6/TxST6l7MhHGe4k0omB6H5V
  artifact: "GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32,GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32-installer"
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

artifacts:
  - path: dist\windows\x86\GrandView-win32-ia32
    name: GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32

  - path: GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32-installer.zip
    name: GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32-installer
