environment:
  nodejs_version: "8.1.0"

# branches:
#   only:
#     - devel

platform:
  - x86
  - x64

install:
  - ps: $env:APP_VERSION = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Install-Product node $env:nodejs_version $env:platform
  # Install modules
  - npm install
  # Install build tools
  - npm install --global --production windows-build-tools
  # Download Meteor
  - ps: Start-FileDownload 'https://s3.amazonaws.com/meteor-windows/InstallMeteor.exe'
  # Install meteor
  - .\installMeteor.exe /passive
  # Restart
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer -Force
  - ps: Start-Sleep -s 5

build_script:
  - echo %platform%
  - npm run build:win:%platform%

after_build:
  - IF "%platform%" == "x64" npm run test:build .dist\win-unpacked/GrandView.exe
  - IF "%platform%" == "x86" npm run test:build .dist\win-ia32-unpacked/GrandView.exe
  - 7z a GrandView-%APPVEYOR_REPO_TAG_NAME%-win32-%platform%-setup.zip "%APPVEYOR_BUILD_FOLDER%\.dist\GrandView Setup %APP_VERSION%.exe"
  - IF "%platform%" == "x64" (7z a GrandView-%APPVEYOR_REPO_TAG_NAME%-win32-%platform%-unpacked.zip "%APPVEYOR_BUILD_FOLDER%\.dist\win-unpacked")
  - IF "%platform%" == "x86" (7z a GrandView-%APPVEYOR_REPO_TAG_NAME%-win32-%platform%-unpacked.zip "%APPVEYOR_BUILD_FOLDER%\.dist\win-ia32-unpacked")
  - rename "%APPVEYOR_BUILD_FOLDER%\.dist\GrandView Setup %APP_VERSION%.exe" "GrandView-%APPVEYOR_REPO_TAG_NAME%-win32-%platform%-setup.exe"

deploy:
  provider: GitHub
  auth_token:
    secure: YjCiFVikmwXzHjASnaAIXVyIif6hdfhnc9UiYZEHemiDGbFAiONuozyxwHRGrVIr
  artifact: "GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)-unpacked,GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)-setup,GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)-setup-exe"
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

artifacts:
  - path: GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)-unpacked.zip
    name: GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)-unpacked

  - path: GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)-setup.zip
    name: GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)-setup

  - path: .dist\GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)-setup.exe
    name: GrandView-$(APPVEYOR_REPO_TAG_NAME)-win32-$(platform)-setup-exe
